drop table SS_RESOURCE_AUTHORITY;
drop table SS_ROLE_AUTHORITY;
drop table SS_USER_ROLE;
drop table SS_RESOURCE;
drop table SS_AUTHORITY;
drop table SS_USER;
drop table SS_ROLE;

create table SS_USER (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
LOGIN_NAME varchar(20) not null unique,
PASSWORD varchar(20),
NAME varchar(20),
EMAIL varchar(30)
);

create unique index SS_USER_LOGIN_NAME_INDEX on SS_USER(LOGIN_NAME);

create table SS_ROLE (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
NAME varchar(20) not null unique
);

create table SS_USER_ROLE (
USER_ID integer not null,
ROLE_ID integer not null,
FOREIGN KEY (ROLE_ID) references SS_ROLE(ID),
FOREIGN KEY (USER_ID) references SS_USER(ID)
);

CREATE TABLE SS_AUTHORITY (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
NAME varchar(20) not null,
DISPLAY_NAME varchar(20) not null
);

create table SS_ROLE_AUTHORITY (
ROLE_ID integer not null,
AUTHORITY_ID integer not null,
FOREIGN KEY (ROLE_ID) references SS_ROLE(ID),
FOREIGN KEY (AUTHORITY_ID) references SS_AUTHORITY(ID)
);

CREATE TABLE SS_RESOURCE (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
RESOURCE_TYPE varchar(20) not null,
VALUE varchar(255) not null,
POSITION float not null
);

create table SS_RESOURCE_AUTHORITY (
AUTHORITY_ID integer not null,
RESOURCE_ID integer not null,
FOREIGN KEY (AUTHORITY_ID) references SS_AUTHORITY(ID),
FOREIGN KEY (RESOURCE_ID) references SS_RESOURCE(ID)
);