drop table SS_USER_ROLE;
drop table SS_USER;
drop table SS_ROLE;

create table SS_USER (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
LOGIN_NAME varchar(20) not null unique,
PASSWORD varchar(20),
NAME varchar(20),
EMAIL varchar(30)
);
create unique index SS_USER_LOGIN_NAME_INDEX on SS_USER(LOGIN_NAME);

create table SS_ROLE (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
NAME varchar(20) not null unique
);

create table SS_USER_ROLE (
USER_ID integer not null,
ROLE_ID integer not null,
FOREIGN KEY (ROLE_ID) references SS_ROLE(ID),
FOREIGN KEY (USER_ID) references SS_USER(ID)
);